### ISSUE TITLE
Better error when nonexisting test file is specified

### ISSUE THREAD

**Issue by pereckerdal** [pereckerdal/overman#86]
Right now, it fails with a generic "Failed to process test files" error

**Comment by pereckerdal** [comment]
The error is actually alright already:

```
Failed to process nonexisting:

module.js:340
  throw err;
        ^
Error: Cannot find module '/Users/peck/prog/overman/nonexisting'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at module.exports (/Users/peck/prog/overman/lib/interfaces/bdd_mocha.js:206:3)
  at Object.<anonymous> (/Users/peck/prog/overman/lib/bin/list_suite.js:62:13)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
```
